<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\Type;

/**
 * AttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function isAlreadyMarked($date, $student)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.onDate = :date')
            ->andWhere('a.student = :student')
            ->orderBy('a.id', 'DESC')
            ->setMaxResults(1)
            ->setParameter('date', $date)
            ->setParameter('student', $student)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findByDate($student, $year = null, $month = null)
    {
        if ($month === null) {
            $month = (int) date('m');
        }

        if ($year === null) {
            $year = (int) date('Y');
        }


        $startDate = new \DateTimeImmutable("$year-$month-01T00:00:00");
        $endDate = $startDate->modify('last day of this month')->setTime(23, 59, 59);

        $qb = $this->createQueryBuilder('a');
        $qb->where('a.onDate BETWEEN :start AND :end');
        $qb->andWhere('a.student = :student');
        $qb->setParameter('start', $startDate, Type::DATE);
        $qb->setParameter('end', $endDate, Type::DATE);
        $qb->setParameter('student', $student);
        $qb->orderBy('a.onDate', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
