<?php

namespace AppBundle\Repository;

/**
 * BookMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
