<?php

namespace AppBundle\Repository;

/**
 * ChildSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
