<?php

namespace AppBundle\Repository;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function countSubjects($user)
    {
        return $this->createQueryBuilder('s')
            ->select('count(s.id)')
            ->where('s.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getValidSubjects($user)
    {
        return $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.role = :parent OR s.role = :no_role')
            ->andWhere('s.user = :user')
            ->setParameter('parent', 'parent')
            ->setParameter('no_role', 'no_role')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }

    public function getSubjectsForTotal($user)
    {
        return $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.outOf != :children')
            ->andWhere('s.user = :user')
            ->setParameter('children', 'children')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }

}
